### ISSUE TITLE
train_lstm.m bug in Matlab 2015a

### ISSUE THREAD

**Issue by cagdasbas** [yechengxi/LightNet#1]
Hi,

I run into trouble of running Main_Char_LSTM.m. 
I've fixed the issue with these changes: 
train_lstm.m line 94-97 

`[  net{1},res.Gate,opts ] = opts.parameters.learning_method( net{1},res.Gate,opts);
[  net{2},res.Input,opts ] = opts.parameters.learning_method (net{2},res.Input,opts );
[  net{3},res.Cell,opts ] = opts.parameters.learning_method( net{3},res.Cell,opts );
[  net{4},res.Fit,opts ] = opts.parameters.learning_method( net{4},res.Fit,opts );`
changed to:
`[  net{1},res.Gate,opts ] = feval(opts.parameters.learning_method,net{1},res.Gate,opts);
[  net{2},res.Input,opts ] = feval(opts.parameters.learning_method,net{2},res.Input,opts );
[  net{3},res.Cell,opts ] = feval(opts.parameters.learning_method, net{3},res.Cell,opts );  
[  net{4},res.Fit,opts ] = feval(opts.parameters.learning_method,net{4},res.Fit,opts );`

**Comment by yechengxi** [comment]
Thank you! We have incorporated this fix.
