### ISSUE TITLE
Split into custom layers

### ISSUE THREAD

**Issue by alejandrojapkin** [yechengxi/LightNet#10]
Is it possible to create split custom layer-wise layers? If so, would you provide an example?
Here's my intended implementation: 
<img width="734" alt="screen shot 2018-05-23 at 12 33 40" src="https://user-images.githubusercontent.com/5109806/40435014-0f7a1a38-5e86-11e8-8ecf-f073f14234a2.png">

**Comment by yechengxi** [comment]
You'd need to write a custom layer for these operations. You can find examples in the LSTM implementation. For this type of operations it may be easier for you to switch to platforms with automatic differentiation.
