### ISSUE TITLE
What's the different of lightnet and matconvnet?

### ISSUE THREAD

**Issue by marksunpeng** [yechengxi/LightNet#3]
Hi guys,
great work! thanks for sharing.

Just one question: what's the different of lightnet and matconvnet? better wrapper function? more convenient choices?

Thanks for your time,
peng

**Comment by yechengxi** [comment]
LightNet is implemented in fewer lines of code and in pure Matlab. There is less redundancy compared to most other platforms. The lines of code is at least an order of magnitude fewer than any other platforms.

It also supports different network architectures such as MLP and RNN.

**Comment by RoyiAvital** [comment]
Looks very very good.

I hope you and other will keep developing it.

**Comment by yechengxi** [comment]
Thanks. LightNet is likely to stay alive for a long time for both theoretical and practical purposes.
