### ISSUE TITLE
Some CNN example files are missing

### ISSUE THREAD

**Issue by sir-avinash** [yechengxi/LightNet#4]
PrepareData_MNIST_CNN and net_init_cnn_mnist are missing and there maybe more. Please check the commented parts in the Main_Template file. %% Also can you please update your comments (especially for the RL example.)

Great job tho!

**Comment by yechengxi** [comment]
Thanks for the comment. We have an example on cifar rather than mnist. And we will provide better documentation in the future. That's on our schedule.
