### ISSUE TITLE
Error with RNNs when "use_nntoolbox" = 1 & "use_gpu" = 0, request for RNN documentation

### ISSUE THREAD

**Issue by Optrode** [yechengxi/LightNet#5]
Hello,
I have been trying to see if I can get more use out of LightNet than I have so far gotten out of the NNToolbox.  I am using MatLab R2016b, with Neural Network toolbox installed.  My PC is a 16-core Xeon system, w/ GTX 1070 GPU.

One issue I have run into is that when I try to run the provided example script "Main_Char_RNN" with `opts.use_nntoolbox=1` and `use_gpu=0`, an error occurs.  I have traced the source of the error to the function "linear_layer.m", line 26:

`y=fc_nntb.forward(I);`

What appears to be happening is that the 'forward' method of the 2dconvolutional layer class returns a 4-D gpuArray, and the remainder of the function is not expecting a gpuArray because use_gpu is set to 0.

I have found that changing this to `y=gather(fc_nntb.forward(I));` fixes the problem, but it does not solve the problem of what to do if you don't want to use GPU at all.  I have found that it is substantially faster simply to set 'use_nntoolbox' to 0.

Also, is there any more documentation available for the LSTM / GRU modules?  I want to apply them to neural spike train data (as binary time series).  I am having some difficulty understanding the data prep and network initialization functions.

Thanks for any help you can provide!

**Comment by yechengxi** [comment]
Hello,

For the RNN example we also noticed that it is significantly faster if we just use CPU and turn off the NN toolbox option. At this moment it looks like the toolbox is relatively new so its efficiency is not fully optimized. 

The documentation is still in progress. The network initialization is similar to the MLP example we provided in the documentation. The difference is that we initialized several networks here to conduct different transforms e.g. input transform, output transform.

The data is organizes as: feature_dim x time_frames x batch_dim .
