### ISSUE TITLE
RNN example can't work

### ISSUE THREAD

**Issue by shipengai** [yechengxi/LightNet#8]
When I run Main_char_RNN.m, some error happend.
错误使用  + 
矩阵维度必须一致。

出错 linear_layer (line 56)
        y=y+bias;

出错 net_ff (line 56)
                [res(layer+1).x,~,~,opts] = linear_layer(
                res(layer).x,net.layers{layer}.weights{1},net.layers{layer}.weights{2},[],
                opts );

出错 rnn_ff (line 46)
        [ net{1},res.Input{f},opts ] = net_ff( net{1},res.Input{f},opts
        );

出错 train_rnn (line 36)
            [ net,res,opts ] = rnn_ff( net,opts );

出错 Main_Char_RNN (line 146)
    [net,opts]=train_rnn(net,opts);

the shape of y is [90,97],the bias's shape is [90,1]

**Comment by JonathanSchmalhoferBMW** [comment]
I do have the same error. Can you tell me how you solved that? Thanks.

**Comment by shipengai** [comment]
Please use matlab2016b or 2017a .

**Comment by JonathanSchmalhoferBMW** [comment]
thx for the hint, I'll try again once I have a proper version available
